server:
  port: 8761
eureka:
  client:
    registerWithEureka: false #单机模式下不需要把自己当作client
    fetchRegistry: false      #单机模式下不需要
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka  #使用简单的认证
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123